User.create(username: "Skywalker", email: "Skywalker@email.com", password: "password")
User.create(username: "Bob", email: "Bob@email.com", password: "password")
User.create(username: "Lord Vader", email: "Vader@email.com", password: "password")
User.create(username: "Star", email: "Star@email.com", password: "password")
User.create(username: "Fred", email: "Fred@email.com", password: "password")
User.create(username: "Garry", email: "Garry@email.com", password: "password")
User.create(username: "Luke", email: "Luke@email.com", password: "password")
User.create(username: "Harry", email: "Harry@email.com", password: "password")
User.create(username: "Groot", email: "Groot@email.com", password: "password")
User.create(username: "Dillion", email: "Dillon@email.com", password: "password")

Project.create(name: "USDJPY", image_url: "/images/forex.jpg", technical_analysis: "sell", user_id: 1)
Project.create(name: "AUDJPY", image_url: "/images/forex.jpg", technical_analysis: "buy", user_id: 2)
Project.create(name: "EURJPY", image_url: "/images/forex.jpg", technical_analysis: "sell", user_id: 3)
Project.create(name: "NZDJPY", image_url: "/images/forex.jpg", technical_analysis: "buy", user_id: 4)
Project.create(name: "EURAUD", image_url: "/images/forex.jpg", technical_analysis: "sell", user_id: 5)
