User.create(username: "Kristen", email: "Kristen@email.com", password: "password")
User.create(username: "The Doctor", email: "DoctorWho@email.com", password: "password")
User.create(username: "Lord Vader", email: "Vader@email.com", password: "password")
User.create(username: "Starbuck", email: "Starbuck@email.com", password: "password")
User.create(username: "Freezy", email: "Iamcold@email.com", password: "password")
User.create(username: "Cheeto Von Tweeto", email: "Drumpf@email.com", password: "password")
User.create(username: "Luke", email: "Skywalker@email.com", password: "password")
User.create(username: "Harry", email: "Harry@email.com", password: "password")
User.create(username: "I am Groot", email: "Groot@email.com", password: "password")
User.create(username: "Arya", email: "AGirlHasNoName@email.com", password: "password")

Project.create(name: "Baby Hat", image_url: "/images/babyhat.jpg", materials: "U.S. size 6 needles, 2 skeins bulky yarn", instructions:"Cast on 20 stitches, knit a hat.", user_id: 1)
Project.create(name: "The Fourth Doctor's Scarf", image_url: "/images/doctorwhoscarf1.gif", materials: "U.S. size 5 needles, 10 skeins worsted weight yarn in a bunch of colors", instructions:"Cast on 50 stitches, knit until you become a time lord.", user_id: 2)
Project.create(name: "Death Star Pillow", image_url: "/images/deathstar.jpg", materials: "U.S. size 4 needles, 2 skeins aran weight yarn", instructions:"Cast on 100 stitches, destroy Princess Leia's planet.", user_id: 3)
Project.create(name: "Coffee Cup Cozy", image_url: "/images/coffeecozy.jpg", materials: "U.S. size 10 needles, 2 skeins super-bulky yarn", instructions:"Cast on 20 stitches, make a cup sweater.", user_id: 4)
Project.create(name: "Comfy Socks", image_url: "/images/socks.jpeg", materials: "U.S. size 9 needles, 2 skeins bulky yarn", instructions:"Cast on 20 stitches, twice, knit a sock, twice.", user_id: 5)
Project.create(name: "A New President", image_url: "/images/trump.jpg", materials: "U.S. size 8 needles, 2 skeins bulky yarn in any color but neon orange", instructions:"Cast on 20 stitches, keep on dreaming....", user_id: 6)
Project.create(name: "Harry Potter Scarf", image_url: "/images/potter.jpg", materials: "U.S. size 7 needles, 2 skeins worsted weight yarn", instructions:"Cast on 20 stitches, hope the sorting hat gives you GRYFFINDOR!", user_id: 8)
Project.create(name: "Baby Groot Amigarumi", image_url: "/images/groot.jpeg", materials: "U.S. size 1 needles, 2 skeins lace yarn", instructions:"Cast on 20 stitches, knit a tiny tree, make him dance!", user_id: 9)
Project.create(name: "Yoda Backpack", image_url: "/images/yoda.jpeg", materials: "U.S. size 3 needles, 2 skeins of green bulky yarn", instructions:"Cast on 20 stitches, knit a Yoda. Now Yoda will always have your back.", user_id: 7)
Project.create(name: "The Stark Family Crest", image_url: "/images/stark.jpeg", materials: "U.S. size 2 needles, 2 skeins fingering/sport weight yarn in black and white", instructions:"Winter is coming; knit faster.", user_id: 10)
